apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: public

commonLabels:
  app: public-api-production
  team: devops

commonAnnotations:
  note: "This is an PRODUCTION deployment"

resources:
  - ns.yaml
  - ../../base

patches:

 # yaml file
 -  target:
      name: public-api
      kind: Deployment
    path: deploy-patch.yaml
 -  target:
      name: cm-private-api
    path:  cm-patch.yaml
 -  target:
      name: public-api
      kind: Ingress
    path:  ingress-patch.yaml
 -  target:
      name: svc-public-api
      kind: Service
    path: svc-patch.yaml


images:
  - name: KUSTOMIZE-DEFINED
    newName: geraldbar/kubelabs_publicapi2
    newTag: 1.0.0