apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: public

commonLabels:
  app: public-api-production
  team: devops

commonAnnotations:
  note: This is an PRODUCTION deployment

resources:
- ns.yaml
- ../../base


 # yaml file
patches:
- path: deploy-patch.yaml
  target:
    kind: Deployment
    name: public-api
- path: cm-patch.yaml
  target:
    name: cm-private-api
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: public-api
- path: svc-patch.yaml
  target:
    kind: Service
    name: svc-public-api


images:
- name: KUSTOMIZE-DEFINED
  newName: geraldbar/kubelabs_publicapi2
  newTag: 5.0.0
